context:
  name: cargo-nextest
  version: "0.9.78"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nextest-rs/nextest/archive/cargo-nextest-${{ version }}.tar.gz
  sha256: cab5f307ca28cca63ba577614a41a7d390731571241d0460e005e2b32d5efac6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
    - cargo-nextest --help

about:
  homepage: https://nexte.st/
  summary: 'A next-generation test runner for Rust'
  description: |
    Cargo Nextest is a next-generation test runner for Rust,
    designed to be fast and efficient.
    It provides advanced features for running and managing tests,
    including parallel execution and detailed reporting.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  repository: https://github.com/nextest-rs/nextest

extra:
  recipe-maintainers:
    - Hofer-Julian
