context:
  name: cargo-nextest
  version: "0.9.96"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nextest-rs/nextest/archive/cargo-nextest-${{ version }}.tar.gz
  sha256: 791e42ea5a5fe6c42713f68e7dab8a9bb769c7e38336262b9ae8d226631d95fe

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-nextest --help

about:
  homepage: https://nexte.st/
  summary: 'A next-generation test runner for Rust'
  description: |
    Cargo Nextest is a next-generation test runner for Rust,
    designed to be fast and efficient.
    It provides advanced features for running and managing tests,
    including parallel execution and detailed reporting.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  repository: https://github.com/nextest-rs/nextest

extra:
  recipe-maintainers:
    - Hofer-Julian
