context:
  name: cargo-nextest
  version: "0.9.101"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nextest-rs/nextest/archive/cargo-nextest-${{ version }}.tar.gz
  sha256: ab1eca47940231c99069736f765c75330440a14627c11e74ab98c3ef81feefc3

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path ./cargo-nextest
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - cargo-nextest --help

about:
  homepage: https://nexte.st/
  summary: A next-generation test runner for Rust
  description: |
    Cargo Nextest is a next-generation test runner for Rust,
    designed to be fast and efficient.
    It provides advanced features for running and managing tests,
    including parallel execution and detailed reporting.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://nexte.st/
  repository: https://github.com/nextest-rs/nextest

extra:
  recipe-maintainers:
    - Hofer-Julian
