context:
  name: cargo-nextest
  version: "0.9.93"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nextest-rs/nextest/archive/cargo-nextest-${{ version }}.tar.gz
  sha256: 319bc72fe5479d0ce9496fa03bdf87e04b335490c446272f7be2912327b1145d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-nextest --help

about:
  homepage: https://nexte.st/
  summary: 'A next-generation test runner for Rust'
  description: |
    Cargo Nextest is a next-generation test runner for Rust,
    designed to be fast and efficient.
    It provides advanced features for running and managing tests,
    including parallel execution and detailed reporting.
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  repository: https://github.com/nextest-rs/nextest

extra:
  recipe-maintainers:
    - Hofer-Julian
